# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

#include apiKey in the command to fetch online license

#Two ways to run this pipeline 
#First is by using script as the step to run the command from Uses in README.md file at https://github.com/katalon-studio/docker-images
#Second is to use the Execute Katalon Studio Tests task
#script requires vmImage to be ubuntu-latest to run the linux commands
#katalonTask requires vmImage to be windows-latest to download the correct version of Katalon Studio

#replace -task:katalonTask@0 section with the following -script section
#- script: docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon katalonc.sh -projectPath=/tmp/project -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey="fdb89052-b651-46fe-ac7c-b7b4b305eb55"
#  displayName: 'Runnning Katalon TS_RegressionTest'

steps:
- task: katalonTask@0 
  displayName: 'Execute Katalon Studio Project'
  inputs:
    version: '7.4.0'
    executeArgs: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey="fdb89052-b651-46fe-ac7c-b7b4b305eb55"'


