# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

#run the pipeline on a linux machine
pool:
  vmImage: 'windows-latest'

#include apiKey in the command to fetch online license
#Command is from Uses in README.md file at https://github.com/katalon-studio/docker-images
steps:
#- script: docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon katalonc.sh -projectPath=/tmp/project -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey="fdb89052-b651-46fe-ac7c-b7b4b305eb55"
#  displayName: 'Runnning Katalon TS_RegressionTest'
- task: katalonTask@0
  inputs:
    version: '7.4.0'
    executeArgs: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey="fdb89052-b651-46fe-ac7c-b7b4b305eb55"'


